FROM node:22-alpine

WORKDIR /app

COPY ban-kanban/package.json ban-kanban/package-lock.json ./
RUN npm install

COPY ban-kanban .

COPY ban-kanban/.env .env

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]