FROM node:22-alpine

WORKDIR /app

COPY ban-kanban/package.json ban-kanban/package-lock.json ./
RUN npm install --production

COPY ban-kanban .

RUN npm run build

ENV $(cat .env.docker | xargs)

EXPOSE 3000

CMD ["npm", "run", "start"]